"""The one place that retires graph entities and relationships.

A fact is retired by setting ``deleted_at``. Every retirement also queues a
projection event, because Neo4j only learns about a removal from that event.
"""
from __future__ import annotations

from datetime import datetime
from typing import Iterable

from sqlalchemy import func, or_
from sqlalchemy.orm import Session

from .models import Entity, EntitySource, GraphProjectionEvent, Relationship, RelationshipSource

# Facts someone entered by hand never disappear because a document did.
HAND_MADE_ORIGIN = "manual"


def retire_relationship(db: Session, relationship: Relationship) -> bool:
    if relationship.deleted_at is not None:
        return False
    relationship.deleted_at = datetime.utcnow()
    db.add(GraphProjectionEvent(event_type="relationship", relationship_id=relationship.id))
    return True


def retire_entity(db: Session, entity: Entity) -> bool:
    if entity.deleted_at is not None:
        return False
    entity.deleted_at = datetime.utcnow()
    db.add(GraphProjectionEvent(event_type="entity", entity_id=entity.id))
    return True


def _retire_edges_of(db: Session, entity: Entity) -> None:
    for relationship in db.query(Relationship).filter(
        or_(Relationship.source_entity_id == entity.id, Relationship.target_entity_id == entity.id),
        Relationship.deleted_at.is_(None),
    ):
        retire_relationship(db, relationship)


def delete_entity_with_edges(db: Session, entity: Entity) -> None:
    """An explicit delete takes the entity's edges with it."""
    _retire_edges_of(db, entity)
    retire_entity(db, entity)


def retire_unsupported(db: Session, *, entity_ids: Iterable[str] = (), relationship_ids: Iterable[str] = (), cascade_edges: bool = False) -> dict[str, int]:
    """Recount the sources of the given facts and retire the generated ones left with none.

    ``cascade_edges`` also retires the edges of a retired entity. Regeneration leaves them alone, because the
    entity comes back moments later and a reviewer's decision on its edges must survive.
    """
    retired = {"entities_retired": 0, "relationships_retired": 0}
    for relationship in db.query(Relationship).filter(Relationship.id.in_(list(relationship_ids))):
        relationship.source_count = db.query(func.count(RelationshipSource.id)).filter_by(relationship_id=relationship.id).scalar() or 0
        if relationship.source_count == 0 and relationship.origin != HAND_MADE_ORIGIN:
            retired["relationships_retired"] += retire_relationship(db, relationship)
    for entity in db.query(Entity).filter(Entity.id.in_(list(entity_ids))):
        entity.source_count = db.query(func.count(EntitySource.id)).filter_by(entity_id=entity.id).scalar() or 0
        if entity.source_count == 0 and entity.origin != HAND_MADE_ORIGIN:
            if cascade_edges:
                _retire_edges_of(db, entity)
            retired["entities_retired"] += retire_entity(db, entity)
    return retired


def drop_document_evidence(db: Session, document_id: str, *, origin: str | None = None) -> dict[str, int]:
    """Remove one document's evidence from the graph, then retire what no longer has any.

    ``origin`` limits the sweep to facts generated by one pipeline (metadata, legal schema) and means the
    facts are being regenerated. Without it the document is going away for good.
    """
    relationship_query = db.query(RelationshipSource.relationship_id).join(Relationship).filter(RelationshipSource.document_id == document_id)
    entity_query = db.query(EntitySource.entity_id).join(Entity).filter(EntitySource.document_id == document_id)
    if origin:
        relationship_query = relationship_query.filter(Relationship.origin == origin)
        entity_query = entity_query.filter(Entity.origin == origin)
    relationship_ids = {row[0] for row in relationship_query}
    entity_ids = {row[0] for row in entity_query}
    db.query(RelationshipSource).filter(RelationshipSource.document_id == document_id, RelationshipSource.relationship_id.in_(relationship_ids)).delete(synchronize_session=False)
    db.query(EntitySource).filter(EntitySource.document_id == document_id, EntitySource.entity_id.in_(entity_ids)).delete(synchronize_session=False)
    return retire_unsupported(db, entity_ids=entity_ids, relationship_ids=relationship_ids, cascade_edges=origin is None)
